### ISSUE TITLE
Example achievement on wiki doesn't work.

### ISSUE THREAD

**Issue by Claycorp** [Lomeli12/AchieveSON#1]
If you copy paste that in or follow the directions it will only make a new achievement page and inside that will be empty.

**Comment by Lomeli12** [comment]
Sorry, the wiki shows changes I've made to the mod but haven't published yet. Use the example on the FTB forums for the time being. http://forum.feed-the-beast.com/threads/1-7-10-achieveson.64692/

**Comment by Claycorp** [comment]
Well thats concerning.... I really don't want to spend hours working on a bunch of stuff just to have the format change. 
Plus the mod doesn't seem to care if the JSON is invalid as i never did see an error. otherwise it would have made more sense.

**Comment by Lomeli12** [comment]
I made some dumb choices with the mod early on. The change of format was a result of me switch over to GSON instead of mainly parsing it like a scrub. As for the error thing, it's been awhile since i touched this, but it should've printed an an error, or like I said I made a dumb choice and didn't do proper exception handling >_<

**Comment by Claycorp** [comment]
Will the new format be out soon? Id rather wait a day or two and start with that then start with the old one and need to rewrite.

**Comment by Lomeli12** [comment]
It is pretty much done, I just got distracted with other projects and never did the finishing touches. I'm not really doing anything ATM (other than posting to this issue), so I can go back and finish it now.

**Comment by Claycorp** [comment]
That would be awesome! There's no rush if you run into anything major. Like i said i just don't want to switch formats in the middle of it. Thanks for the quick replies BTW.

**Comment by Lomeli12** [comment]
No problem =P
